"""empty message

Revision ID: 12f9e436b3e6
Revises: 
Create Date: 2018-08-28 21:43:18.752636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f9e436b3e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('hobby', sa.String(length=126), nullable=True))
    op.add_column('student', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'name')
    op.drop_column('student', 'hobby')
    op.drop_column('student', 'age')
    # ### end Alembic commands ###
